# Generated by Django 4.1.2 on 2023-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_user_password_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(blank=True, default='Enter Description', max_length=500),
        ),
    ]
