# Generated by Django 4.1.2 on 2023-02-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_user_desc_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
